version: "3.8"

services:
  angular:
    image: youssefabu/media-network-angular:latest
    container_name: contacts_angular
    restart: always
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=dev
    networks:
      - shared-network

  nginx:
    image: nginx
    container_name: contacts_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - shared-network

networks:
  shared-network:
    external: true
