replicaCount: 1

frontend: true
namespace: frontend


image:
  repository: youssefabu/media-network-angular
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 4000
  nodePort: 4000



autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70

