apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
        - name: angular
          image: youssefabu/media-network-angular:latest
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: dev
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
