apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: angular-hpa
  namespace: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: angular-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
